# Don't read /etc/hosts
no-hosts

# Don't poll /etc/resolv.conf for changes
no-poll

# Log queries for debugging if needed (uncomment below if needed)
# log-queries

# Direct all *.test domain queries to 127.0.0.1
address=/.test/127.0.0.1
address=/.php82.test/127.0.0.1
address=/.php83.test/127.0.0.1

# Listen on all container interfaces
listen-address=0.0.0.0
bind-interfaces
